#!/bin/sh

case "$1" in
    purge)
        rm -rf "{{{path.logDirectory}}}"
        deluser --remove-home --system "{{{unix.user}}}" >/dev/null 2>&1
    ;;
    remove)
        deluser --remove-home --system "{{{unix.user}}}" >/dev/null 2>&1
    ;;

esac

exit 0
